const schedulerGl: any = {
  VERTEX_SHADER: 35633,
  FRAGMENT_SHADER: 35632,
  ARRAY_BUFFER: 34962,
  TEXTURE_2D: 3553,
  RGBA: 6408,
  UNSIGNED_BYTE: 5121,
  BLEND: 3042,
  ONE_MINUS_SRC_ALPHA: 771,
  ONE: 1,
  TRIANGLES: 4,
  COLOR_BUFFER_BIT: 16384,
  COMPILE_STATUS: 35713,
  LINK_STATUS: 35714,
  TEXTURE0: 33984,
  CLAMP_TO_EDGE: 33071,
  NEAREST: 9728,
  LINEAR: 9729,
  TEXTURE_WRAP_S: 10242,
  TEXTURE_WRAP_T: 10243,
  TEXTURE_MIN_FILTER: 10241,
  TEXTURE_MAG_FILTER: 10240,
  UNPACK_PREMULTIPLY_ALPHA_WEBGL: 37440,
  STATIC_DRAW: 35044,
  FLOAT: 5126,
  createShader: () => ({}),
  createProgram: () => ({}),
  createBuffer: () => ({}),
  createTexture: () => ({}),
  deleteTexture: () => {},
  shaderSource: () => {},
  compileShader: () => {},
  getShaderParameter: () => true,
  attachShader: () => {},
  linkProgram: () => {},
  getProgramParameter: () => true,
  bindBuffer: () => {},
  bufferData: () => {},
  getAttribLocation: () => 0,
  getUniformLocation: () => ({}),
  viewport: () => {},
  useProgram: () => {},
  uniform2f: () => {},
  uniform4f: () => {},
  uniform1i: () => {},
  enable: () => {},
  blendFunc: () => {},
  clearColor: () => {},
  clear: () => {},
  bindTexture: () => {},
  texParameteri: () => {},
  texImage2D: () => {},
  pixelStorei: () => {},
  activeTexture: () => {},
  enableVertexAttribArray: () => {},
  vertexAttribPointer: () => {},
  drawArrays: () => {},
  getExtension: () => null,
};

const scheduler2d: any = {
  font: "",
  fillStyle: "",
  strokeStyle: "",
  textAlign: "center",
  textBaseline: "middle",
  lineWidth: 0,
  save: () => {},
  restore: () => {},
  beginPath: () => {},
  moveTo: () => {},
  lineTo: () => {},
  quadraticCurveTo: () => {},
  closePath: () => {},
  fill: () => {},
  stroke: () => {},
  fillRect: () => {},
  clearRect: () => {},
  translate: () => {},
  rotate: () => {},
  setTransform: () => {},
  fillText: () => {},
  measureText: (text: string) => ({ width: text.length * 8 }),
  getImageData: () => ({ data: new Uint8ClampedArray([0, 0, 0, 0]) }),
};

HTMLCanvasElement.prototype.getContext = function (type: string) {
  return type === "2d" ? scheduler2d : schedulerGl;
} as any;

if (typeof globalThis.ResizeObserver === "undefined") {
  (globalThis as any).ResizeObserver = class {
    observe() {}
    unobserve() {}
    disconnect() {}
  };
}
