version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    environment:
      - MONGODB_URI=mongodb://mongo:27017/jspsych-builder
      # Agrega tus variables de Cloudinary aquí
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo_data:
