import { ParameterType } from "jspsych";

var version = "2.1.0";

const info = {
  name: "SurveyHtmlFormComponent",
  version,
  parameters: {
    /** HTML formatted string containing all the input elements to display. Every element has to have its own distinctive name attribute. The <form> tag must not be included and is generated by the plugin. */
    html: {
      type: ParameterType.HTML_STRING,
      default: null,
    },
    /** HTML formatted string to display at the top of the page above all the questions. */
    preamble: {
      type: ParameterType.HTML_STRING,
      default: null,
    },
    /** The text that appears on the button to finish the trial. */
    button_label: {
      type: ParameterType.STRING,
      default: "Continue",
    },
    /** The HTML element ID of a form field to autofocus on. */
    autofocus: {
      type: ParameterType.STRING,
      default: "",
    },
    /** Retrieve the data as an array e.g. [{name: "INPUT_NAME", value: "INPUT_VALUE"}, ...] instead of an object e.g. {INPUT_NAME: INPUT_VALUE, ...}. */
    dataAsArray: {
      type: ParameterType.BOOL,
      default: false,
    },
    /** Setting this to true will enable browser auto-complete or auto-fill for the form. */
    autocomplete: {
      type: ParameterType.BOOL,
      default: false,
    },
    /** Position coordinates for the survey form. x and y should be between -1 and 1, mapped to -50vw/vh to 50vw/vh. */
    coordinates: {
      type: ParameterType.OBJECT,
      default: { x: 0, y: 0 },
    },
  },
  data: {
    /**  An object containing the response for each input. The object will have a separate key (variable) for the response to each input, with each variable being named after its corresponding input element. Each response is a string containing whatever the participant answered for this particular input. This will be encoded as a JSON string when data is saved using the `.json()` or `.csv()` functions. */
    response: {
      type: ParameterType.OBJECT,
    },
    /** The response time in milliseconds for the participant to make a response. */
    rt: {
      type: ParameterType.INT,
    },
  },
  // prettier-ignore
  citations: {
    "apa": "de Leeuw, J. R., Gilbert, R. A., & Luchterhandt, B. (2023). jsPsych: Enabling an Open-Source Collaborative Ecosystem of Behavioral Experiments. Journal of Open Source Software, 8(85), 5351. https://doi.org/10.21105/joss.05351 ",
    "bibtex": '@article{Leeuw2023jsPsych, 	author = {de Leeuw, Joshua R. and Gilbert, Rebecca A. and Luchterhandt, Bj{\\" o}rn}, 	journal = {Journal of Open Source Software}, 	doi = {10.21105/joss.05351}, 	issn = {2475-9066}, 	number = {85}, 	year = {2023}, 	month = {may 11}, 	pages = {5351}, 	publisher = {Open Journals}, 	title = {jsPsych: Enabling an {Open}-{Source} {Collaborative} {Ecosystem} of {Behavioral} {Experiments}}, 	url = {https://joss.theoj.org/papers/10.21105/joss.05351}, 	volume = {8}, }  '
  },
};

/**
 * SurveyHtmlFormComponent - handles HTML form surveys with custom inputs
 * Stores response data internally like sketchpad, exposes via getters
 */
class SurveyHtmlFormComponent {
  private jsPsych: any;
  private response: any = null;
  private rt: number = 0;
  private startTime: number = 0;

  constructor(jsPsych: any) {
    this.jsPsych = jsPsych;
  }

  static info = info;

  render(display_element: HTMLElement, trial: any) {
    // Helper to map coordinate values
    const mapValue = (value: number): number => {
      if (value < -1) return -50;
      if (value > 1) return 50;
      return value * 50;
    };

    // Create main container with positioning
    const mainContainer = document.createElement("div");
    mainContainer.id = "jspsych-survey-html-form-main";
    mainContainer.style.position = "relative";
    display_element.appendChild(mainContainer);

    // Create form container with coordinates
    const formContainer = document.createElement("div");
    formContainer.id = "jspsych-survey-html-form-container";
    formContainer.style.position = "relative";

    const xVw = mapValue(trial.coordinates.x);
    const yVh = mapValue(trial.coordinates.y);
    formContainer.style.left = `${xVw}vw`;
    formContainer.style.top = `${yVh}vh`;

    mainContainer.appendChild(formContainer);

    var html = "";
    if (trial.preamble !== null) {
      html +=
        '<div id="jspsych-survey-html-form-preamble" class="jspsych-survey-html-form-preamble">' +
        trial.preamble +
        "</div>";
    }
    if (trial.autocomplete) {
      html += '<form id="jspsych-survey-html-form">';
    } else {
      html += '<form id="jspsych-survey-html-form" autocomplete="off">';
    }
    html += trial.html;
    html +=
      '<input type="submit" id="jspsych-survey-html-form-next" class="jspsych-btn jspsych-survey-html-form" value="' +
      trial.button_label +
      '"></input>';
    html += "</form>";
    formContainer.innerHTML = html;
    if (trial.autofocus !== "") {
      var focus_elements = display_element.querySelectorAll(
        "#" + trial.autofocus
      );
      if (focus_elements.length === 0) {
        console.warn("No element found with id: " + trial.autofocus);
      } else if (focus_elements.length > 1) {
        console.warn(
          'The id "' +
            trial.autofocus +
            '" is not unique so autofocus will not work.'
        );
      } else {
        (focus_elements[0] as HTMLElement).focus();
      }
    }
    formContainer
      .querySelector("#jspsych-survey-html-form")!
      .addEventListener("submit", (event) => {
        event.preventDefault();
        var endTime = performance.now();
        this.rt = Math.round(endTime - this.startTime);
        var this_form = formContainer.querySelector(
          "#jspsych-survey-html-form"
        );
        var question_data = this.serializeArray(this_form);
        if (!trial.dataAsArray) {
          question_data = this.objectifyForm(question_data);
        }
        this.response = question_data;
      });
    this.startTime = performance.now();
  }

  private serializeArray(form: any) {
    var serialized = [];
    for (var i = 0; i < form.elements.length; i++) {
      var field = form.elements[i];
      if (
        !field.name ||
        field.disabled ||
        field.type === "file" ||
        field.type === "reset" ||
        field.type === "submit" ||
        field.type === "button"
      )
        continue;
      if (field.type === "select-multiple") {
        for (var n = 0; n < field.options.length; n++) {
          if (!field.options[n].selected) continue;
          serialized.push({
            name: field.name,
            value: field.options[n].value,
          });
        }
      } else if (
        (field.type !== "checkbox" && field.type !== "radio") ||
        field.checked
      ) {
        serialized.push({
          name: field.name,
          value: field.value,
        });
      }
    }
    return serialized;
  }

  private objectifyForm(formArray: any) {
    var returnArray: any = {};
    for (var i = 0; i < formArray.length; i++) {
      returnArray[formArray[i]["name"]] = formArray[i]["value"];
    }
    return returnArray;
  }

  getResponse() {
    return this.response;
  }

  getRT() {
    return this.rt;
  }

  destroy() {
    // Cleanup if needed
  }
}

export { SurveyHtmlFormComponent as default };
