import type { DocSection } from "./types";

export const SessionLocalSection: DocSection = {
  id: "session-local",
  title: "Session — Local Mode",
  content: `# Session — Local Mode

Generated by the local **Run Experiment** code path.

## Identity and display name

The durable \`sessionId\` is a UUID. A structured name configured in **Builder → Settings → Session Name** is stored separately as \`displayName\`; changing it never changes session identity or file ownership.

| Token | Description | Formats / Options |
|---|---|---|
| \`date\` | Current date | \`YYYYMMDD\`, \`DD-MM-YYYY\`, \`MM-DD-YYYY\`, \`YYYY-MM-DD\` |
| \`time\` | Current time | \`HHmmss\`, \`HH-mm\`, \`HH-mm-ss\` |
| \`randomAlpha\` | Random alphanumeric | Configurable length |
| \`customText\` | Researcher-defined text | Any string |
| \`counter\` | Server-assigned participant number | Configurable padding |

The generated display name can look like \`20260506_003\`, while the UUID remains the stable key in \`db.json\`, IndexedDB, HTTP, and participant files.

## Session start flow

\`localStorage\` and \`sessionStorage\` keys are prefixed with \`expbuilder:local:<experimentID>:\`. A tab owns its own session. Before resuming a candidate, the browser verifies that the exact session exists for the current experiment, is incomplete, has a positive participant number, and is not active in another tab.

\`\`\`mermaid
sequenceDiagram
  participant P as Browser tab
  participant BS as Browser storage
  participant API as Express API
  participant IDB as IndexedDB outbox
  participant S as Socket.IO

  P->>BS: Read experiment/tab-scoped candidate
  P->>API: GET exact persisted session
  alt valid incomplete candidate
    API-->>P: Resume UUID and participant number
  else missing or completed
    P->>P: Generate a new UUID
    P->>API: POST /api/append-result/:id
    API-->>P: Strict ACK and participant number
  end
  P->>API: PATCH displayName when configured
  P->>IDB: Open experiment/session outbox
  P->>S: Load with timeout and join with ACK
  Note over P,S: Socket failure does not block persistence
\`\`\`

If the persisted candidate cannot be verified because HTTP is unavailable or invalid, startup is blocked. The browser does not silently create a replacement that could strand pending data.

## IndexedDB-first persistence

Every trial is stored in IndexedDB before its PUT begins:

\`\`\`js
on_data_update: function(data) {
  localOutbox.enqueue(data);
}
\`\`\`

Each outbox record has \`experimentID\`, \`sessionId\`, a stable \`eventId\`, integer \`sequence\`, payload, status, retry count, and timestamps. A single worker sends records in sequence with bounded retry. Only a successful JSON response whose \`eventId\` and \`sequence\` match marks a record acknowledged. HTTP errors, invalid JSON, mismatched ACKs, and network failures leave it recoverable.

Acknowledged records remain in IndexedDB until final completion is confirmed, so a browser reload can replay any unresolved work idempotently.

## Completion

\`on_finish\` waits for the outbox and submits the exact expected count and last sequence:

\`\`\`js
const stats = await localOutbox.waitForIdle();
if (stats.pending !== 0 || stats.acknowledged !== stats.total) {
  throw new Error('Results remain pending');
}
const response = await fetch('/api/complete-session/' + experimentID, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    sessionId: trialSessionId,
    expectedEventCount: stats.total,
    lastSequence: stats.lastSequence
  })
});
\`\`\`

The server only marks the session completed when every declared sequence exists. IndexedDB and browser identity are cleared only after the response confirms the same count and last sequence. Otherwise the completion screen reports recoverable pending data.

## Socket.IO presence

Socket.IO is optional and only reports transient connection presence. Its script has \`onerror\` and a finite timeout; join/update events require ACKs and an already persisted session. Disconnecting removes presence but never changes or deletes durable session data.

## System metadata

The browser records diagnostic metadata such as browser, version, OS, resolution, language, user agent, and ISO \`startedAt\`. Results UI dates come only from validated persisted timestamps; presence \`connectedAt\` is displayed separately.

## Participant files

\`window.JSPSYCH_FILE_UPLOAD_ENDPOINT\` points to \`/api/participant-files/<experimentID>\`. Uploads require an existing session UUID. Disk files and their \`db.json\` records are committed or rolled back together on failure, and filenames use sanitized identity plus a UUID to prevent collision.
`,
};
