import type { DocSection } from "./types";

export const PluginsSection: DocSection = {
  id: "plugins",
  title: "Standard jsPsych Plugins",
  content: `# Standard jsPsych Plugins

Builder includes **57 official plugins** from jsPsych v8. Metadata (parameters, types, defaults, generated data) is in \`server/metadata/*.json\`.

## Loading by Mode

| Mode | Source | What is loaded |
|---|---|---|
| Local (preview) | \`/bundle/jspsych-bundle.js\` | Full bundle (all plugins) |
| Published | unpkg CDN | **Only the plugins used** in the experiment |

In published mode, \`experiments.js\` analyzes the trials and only includes the \`<script>\` tags for the plugins that the experiment actually needs.

## Full List of Available Plugins

### Stimulus + Response

| Plugin | Stimulus | Response |
|---|---|---|
| \`jsPsychHtmlKeyboardResponse\` | HTML | Keyboard |
| \`jsPsychHtmlButtonResponse\` | HTML | Buttons |
| \`jsPsychHtmlSliderResponse\` | HTML | Slider |
| \`jsPsychImageKeyboardResponse\` | Image | Keyboard |
| \`jsPsychImageButtonResponse\` | Image | Buttons |
| \`jsPsychImageSliderResponse\` | Image | Slider |
| \`jsPsychAudioKeyboardResponse\` | Audio | Keyboard |
| \`jsPsychAudioButtonResponse\` | Audio | Buttons |
| \`jsPsychAudioSliderResponse\` | Audio | Slider |
| \`jsPsychVideoKeyboardResponse\` | Video | Keyboard |
| \`jsPsychVideoButtonResponse\` | Video | Buttons |
| \`jsPsychVideoSliderResponse\` | Video | Slider |

### Surveys

| Plugin | Description |
|---|---|
| \`jsPsychSurveyMultiChoice\` | Multiple choice |
| \`jsPsychSurveyMultiSelect\` | Multiple selection |
| \`jsPsychSurveyText\` | Free text |
| \`jsPsychSurveyLikert\` | Likert scale |
| \`jsPsychSurveyHtmlForm\` | Custom HTML form |
| \`jsPsychSurvey\` | Composite survey (multiple types) |

### Specialized

| Plugin | Description |
|---|---|
| \`jsPsychAnimation\` | Animation (image sequence) |
| \`jsPsychAudioSliderResponse\` | Audio + slider |
| \`jsPsychBrowserCheck\` | Compatibility check |
| \`jsPsychCallFunction\` | Execute arbitrary function |
| \`jsPsychCanvasKeyboardResponse\` | Canvas + keyboard |
| \`jsPsychCanvasButtonResponse\` | Canvas + buttons |
| \`jsPsychCanvasSliderResponse\` | Canvas + slider |
| \`jsPsychCategorizeAnimation\` | Categorize animation |
| \`jsPsychCategorizeHtml\` | Categorize HTML |
| \`jsPsychCategorizeImage\` | Categorize image |
| \`jsPsychCloze\` | Cloze text |
| \`jsPsychExternalHtml\` | External HTML (iframe) |
| \`jsPsychFreeSort\` | Free sorting |
| \`jsPsychFullscreen\` | Fullscreen |
| \`jsPsychHtmlAudioResponse\` | HTML + audio response |
| \`jsPsychHtmlVideoResponse\` | HTML + video response |
| \`jsPsychIatHtml\` | IAT (Implicit Association Test) |
| \`jsPsychIatImage\` | IAT with images |
| \`jsPsychInitialization\` | Initialization |
| \`jsPsychInstructions\` | Instruction pages |
| \`jsPsychMaxDiff\` | MaxDiff (best-worst scaling) |
| \`jsPsychMirrorCamera\` | Mirror camera |
| \`jsPsychMultiImageKeyboardResponse\` | Multiple images + keyboard |
| \`jsPsychMultiImageButtonResponse\` | Multiple images + buttons |
| \`jsPsychMultiImageSliderResponse\` | Multiple images + slider |
| \`jsPsychPreload\` | Resource preloading |
| \`jsPsychReconstruction\` | Reconstruction |
| \`jsPsychResize\` | Resize window |
| \`jsPsychSameDifferentHtml\` | Same/Different with HTML |
| \`jsPsychSameDifferentImage\` | Same/Different with images |
| \`jsPsychSerialReactionTimeMouse\` | SRT with mouse |
| \`jsPsychSerialReactionTime\` | SRT with keyboard |
| \`jsPsychSketchpad\` | Drawing (native jsPsych) |
| \`jsPsychVirtualChinrest\` | Virtual chinrest |
| \`jsPsychVisualSearchCircle\` | Visual search (circles) |
| \`jsPsychWebgazerCalibrate\` | Eye tracking — calibrate |
| \`jsPsychWebgazerInitCamera\` | Eye tracking — start camera |
| \`jsPsychWebgazerValidate\` | Eye tracking — validate |

## Standard Data Generated by All Plugins

\`\`\`js
{
trial_type: "html-keyboard-response",
trial_index: 5,
time_elapsed: 8240,
rt: 840,
response: "f",
stimulus: "<p>Press F or J</p>",
// + Builder-injected fields:
trial_id: 123,
builder_id: "uuid-abc",
trial_name: "Encoding Task",
isInLoop: false,
branches: [],
branchConditions: [],
// + Session fields (published mode):
clientTimestamp: 1715030450123,
sessionId: "20260506_003",
experimentID: "exp-123",
}
\`\`\`
`,
};
