import type { DocSection } from "./types";

export const DataFormatSection: DocSection = {
  id: "data-format",
  title: "Data Format Reference",
  content: `# Data Format Reference

Each trial generates a data object with fields from multiple sources. This is the complete reference.

## jsPsych Fields (core)

| Field | Type | Description |
|---|---|---|
| \`trial_type\` | string | Plugin name (e.g. \`"html-keyboard-response"\`) |
| \`trial_index\` | number | 0-based index in the timeline |
| \`time_elapsed\` | number | ms since experiment start |
| \`internal_node_id\` | string | Internal jsPsych node ID |
| \`rt\` | number | null | Reaction time in ms |
| \`response\` | any | Participant's response |
| \`stimulus\` | string | Presented stimulus |
| \`correct\` | boolean | null | Whether the response was correct |
| \`correct_response\` | any | null | Expected correct response |

## Builder-Injected Fields (trial-level)

| Field | Type | Generated by | Description |
|---|---|---|---|
| \`trial_id\` | number | \`useTrialCode.ts\` | Numeric trial ID in the DB |
| \`builder_id\` | string (UUID) | \`useTrialCode.ts\` | Stable UUID for resume and branching |
| \`trial_name\` | string | \`useTrialCode.ts\` | Trial name in the Builder |
| \`isInLoop\` | boolean | \`useTrialCode.ts\` | Whether the trial is inside a loop |
| \`branches\` | string[] | \`useTrialCode.ts\` | UUIDs of target trials for branch |
| \`branchConditions\` | object[] | \`useTrialCode.ts\` | Conditions that led to this trial |

## Builder-Injected Fields (session-level, published mode)

| Field | Type | Generated by | Description |
|---|---|---|---|
| \`clientTimestamp\` | number | \`PublicConfiguration.ts\` | \`Date.now()\` at trial time |
| \`sessionId\` | string | \`PublicConfiguration.ts\` | Current session ID |
| \`experimentID\` | string | \`PublicConfiguration.ts\` | Experiment ID in Firebase |

## DynamicPlugin Fields

Format: \`[ComponentType]_[Index]_[Property]\`

| Component | Generated fields |
|---|---|
| TextComponent | (no data generated) |
| ImageComponent | \`ImageComponent_N_stimulus\` |
| AudioComponent | (no data generated) |
| VideoComponent | (no data generated) |
| HtmlComponent | (no data generated) |
| SketchpadComponent | \`SketchpadComponent_N_strokes\`, \`SketchpadComponent_N_png\` |
| ButtonResponseComponent | \`ButtonResponseComponent_N_response\`, \`ButtonResponseComponent_N_rt\` |
| KeyboardResponseComponent | \`KeyboardResponseComponent_N_response\`, \`KeyboardResponseComponent_N_rt\` |
| SliderResponseComponent | \`SliderResponseComponent_N_response\`, \`SliderResponseComponent_N_rt\` |
| InputResponseComponent | \`InputResponseComponent_N_response\`, \`InputResponseComponent_N_rt\` |
| ClickResponseComponent | \`ClickResponseComponent_N_response\` (array \`[x, y]\`), \`ClickResponseComponent_N_rt\` |
| AudioResponseComponent | \`AudioResponseComponent_N_response\` (base64), \`AudioResponseComponent_N_rt\` |
| FileUploadResponseComponent | \`FileUploadResponseComponent_N_response\` (URL) |
| SurveyComponent | \`SurveyComponent_N_response\` (object \`{ questionName: answer }\`) |

## Extension Fields

| Extension | Field | Type |
|---|---|---|
| Mouse Tracking | \`mouse_tracking_data\` | \`{ x, y, t, event }[]\` |
| Record Video | \`record_video_data\` | string (base64) |
| WebGazer | \`webgazer_data\` | \`{ x, y, t }[]\` |
| WebGazer | \`webgazer_targets\` | string[] |

## Global Variables in Experiment Scope

| Variable | Scope | Description |
|---|---|---|
| \`jsPsych\` | Global | jsPsych instance |
| \`timeline\` | Global | Experiment timeline array |
| \`trialSessionId\` | IIFE | Current session ID |
| \`participantNumber\` | IIFE | Participant number |
| \`metadata\` | IIFE | System metadata |
| \`pendingDataSaves\` | IIFE | In-flight fetch promises (local) |
| \`socket\` | IIFE | Socket.IO client (local) |
| \`TrialDB\` | Global | IndexedDB wrapper (published) |
| \`BATCH_CONFIG\` | IIFE | Batching config (published) |

## localStorage Keys Used by the Experiment

| Key | When written | When cleared |
|---|---|---|
| \`jsPsych_currentSessionId\` | At session start | \`on_finish\` (success) |
| \`jsPsych_participantNumber\` | When number received | \`on_finish\` (success) |
| \`jsPsych_resumeTrial\` | Each \`on_data_update\` | \`on_finish\` (success) |
| \`jsPsych_jumpToTrial\` | Repeat/jump triggered | When consumed in \`conditional_function\` |
| \`jsPsych_jumpReload\` | \`sessionStorage\` | At experiment start (anti-loop guard) |
`,
};
